#include "julretsu/RestorePoints.hpp"
#include "julretsu/I18n.hpp"
#include <fstream>
#include <chrono>
#include <atomic>
#include <ctime>
#include <algorithm>
namespace julretsu {
namespace {
std::filesystem::path folder(const std::filesystem::path& file){auto path=file;path+=".history";return path;}
bool managed(const std::filesystem::path& path){auto name=path.filename().string();if(path.extension()!=".julretsu"||!(name.starts_with("auto-")||name.starts_with("point-")))return false;auto start=name.find('-')+1;return name.substr(start,name.size()-start-9).find_first_not_of("0123456789-")==std::string::npos;}
}
std::vector<RestorePoint> restore_points(const std::filesystem::path& file){
    std::vector<RestorePoint> result;auto dir=folder(file);if(!std::filesystem::exists(dir))return result;
    for(const auto& entry:std::filesystem::directory_iterator(dir))if(entry.is_regular_file()&&!entry.is_symlink()&&managed(entry.path())){
        std::string label;auto note=entry.path();note+=".label";std::ifstream in(note,std::ios::binary);if(in){char text[256];in.read(text,sizeof text);label.assign(text,std::size_t(in.gcount()));}
        if(label.empty())label=entry.path().stem().string();result.push_back({entry.path(),label});
    }
    std::sort(result.begin(),result.end(),[](const auto& a,const auto& b){return std::filesystem::last_write_time(a.path)>std::filesystem::last_write_time(b.path);});return result;
}
std::filesystem::path create_restore_point(const std::filesystem::path& file,const std::vector<DocumentSheet>& document,std::string label,bool automatic){
    if(file.empty())throw std::runtime_error(tr("Save the workbook before creating restore points."));
    if(label.size()>256)throw std::runtime_error(tr("Restore point names are limited to 256 bytes."));
    auto dir=folder(file);if(std::filesystem::is_symlink(dir))throw std::runtime_error(tr("The history folder must not be a symbolic link."));std::filesystem::create_directories(dir);
    auto existing=restore_points(file);if(!automatic&&std::count_if(existing.begin(),existing.end(),[](const auto& p){return p.path.filename().string().starts_with("point-");})>=100)throw std::runtime_error(tr("Keep at most 100 named restore points per workbook."));
    static std::atomic<unsigned> serial{};auto stamp=std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
    auto path=dir/((automatic?"auto-":"point-")+std::to_string(stamp)+"-"+std::to_string(serial++)+".julretsu");if(std::filesystem::exists(path))throw std::runtime_error(tr("Could not create a unique restore point."));
    for(const auto& s:document)(void)deserialize_sheet(s.bytes);write_document(path,document);auto note=path;note+=".label";auto now=std::time(nullptr);char stamp_text[40]{};std::strftime(stamp_text,sizeof stamp_text,"%Y-%m-%d %H:%M:%S",std::localtime(&now));write_file_atomic(note,std::string(stamp_text)+"  "+label.substr(0,230));
    // Only files generated by this component are eligible for automatic retention.
    if(automatic){auto all=restore_points(file);unsigned count=0;for(const auto& point:all)if(point.path.filename().string().starts_with("auto-")&&++count>20){std::error_code error;std::filesystem::remove(point.path,error);auto text=point.path;text+=".label";std::filesystem::remove(text,error);}}
    return path;
}
WorkbookDifference compare_documents(const std::vector<DocumentSheet>& current,const std::vector<DocumentSheet>& target){
    WorkbookDifference diff;std::map<std::string,WorkbookData> before,after;for(const auto& s:current)before.emplace(s.name,deserialize_sheet(s.bytes));for(const auto& s:target)after.emplace(s.name,deserialize_sheet(s.bytes));std::set<std::string> names;for(const auto& [n,s]:before)names.insert(n);for(const auto& [n,s]:after)names.insert(n);
    for(const auto& name:names){if(!before.contains(name)||!after.contains(name)){++diff.metadata;diff.details.push_back(name+": "+tr(before.contains(name)?"Worksheet removed":"Worksheet added"));}
        auto a=before.contains(name)?before.at(name):WorkbookData{},b=after.contains(name)?after.at(name):WorkbookData{};
        std::map<CellCoord,Input> old,now;for(const auto& e:a.data.cells)old[e.coord]=e.input;for(const auto& e:b.data.cells)now[e.coord]=e.input;std::set<CellCoord> cells;for(const auto& [c,v]:old)cells.insert(c);for(const auto& [c,v]:now)cells.insert(c);
        auto text=[](const Input& input){if(auto f=std::get_if<FormulaInput>(&input))return f->source;return std::visit([](const auto& v)->std::string{using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,FormulaInput>)return v.source;else return display(Value{v});},input);};
        for(auto c:cells)if(old[c]!=now[c]){++diff.cells;if(diff.details.size()<100)diff.details.push_back(name+"!"+std::get<std::string>(to_a1(c))+": "+text(old[c]).substr(0,120)+" -> "+text(now[c]).substr(0,120));}
        Sheet x,y;auto xr=x.apply(a.data),yr=y.apply(b.data);if(!xr.accepted||!yr.accepted)throw std::runtime_error(tr("Invalid restore point."));
        if(x.cell_styles()!=y.cell_styles()||x.row_styles()!=y.row_styles()||x.validation_rules()!=y.validation_rules()||x.tables()!=y.tables()||a.script!=b.script){++diff.metadata;if(diff.details.size()<100)diff.details.push_back(name+": "+tr("Formatting, rules, tables or Lua code changed"));}
    }
    if(current.size()==target.size())for(std::size_t i=0;i<current.size();++i)if(current[i].name!=target[i].name){++diff.metadata;diff.details.push_back(tr("Worksheet order changed"));break;}
    return diff;
}
}
